# Generated by Django 5.0.2 on 2024-02-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourismSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('nature', models.BooleanField(default=False)),
                ('culture', models.BooleanField(default=False)),
                ('adventure', models.BooleanField(default=False)),
                ('hiking', models.BooleanField(default=False)),
                ('mountain_biking', models.BooleanField(default=False)),
                ('exploring_wildlife_sanctuaries', models.BooleanField(default=False)),
                ('national_park_safaris', models.BooleanField(default=False)),
                ('bird_watching', models.BooleanField(default=False)),
                ('exploring_lakes', models.BooleanField(default=False)),
                ('visits_to_sacred_sites', models.BooleanField(default=False)),
                ('visits_to_temples_and_monasteries', models.BooleanField(default=False)),
                ('homestays_with_local_communities', models.BooleanField(default=False)),
                ('visiting_historical_sites', models.BooleanField(default=False)),
                ('visiting_museums', models.BooleanField(default=False)),
                ('attending_cultural_events', models.BooleanField(default=False)),
                ('rafting_in_white_water', models.BooleanField(default=False)),
                ('paragliding', models.BooleanField(default=False)),
                ('rock_climbing', models.BooleanField(default=False)),
                ('bungee_jumping', models.BooleanField(default=False)),
                ('zip_lining', models.BooleanField(default=False)),
                ('canyoning', models.BooleanField(default=False)),
                ('horse_riding', models.BooleanField(default=False)),
                ('trekking_in_the_mountains', models.BooleanField(default=False)),
                ('jungle_safari', models.BooleanField(default=False)),
                ('hot_air_ballooning', models.BooleanField(default=False)),
                ('skydiving', models.BooleanField(default=False)),
            ],
        ),
    ]
