# Generated by Django 5.0.2 on 2024-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TouristSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismsite',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
